#!/usr/bin/env bash

CC_FLAGS="-std=c++14 -Wall -O2 -lm -Wl,-stack_size -Wl,0x10000000"
CC=g++

TARGET=$1
SOURCE="src/${TARGET%?}/${TARGET: -1}.cpp"

if [[ ! -f $SOURCE ]]; then
  echo "File not found: $SOURCE"
  exit 1
elif [[ ! $SOURCE -nt $TARGET ]]; then
  echo "'$TARGET' is up to date."
else
  $CC $CC_FLAGS -o $TARGET $SOURCE
fi
